name: ci

on: [push]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.6
      - run: terraform init
      - run: terraform validate
      - run: terraform fmt -check
